### ISSUE TITLE
Option for put the trigger values manually 

### ISSUE THREAD

**Issue by cualquiercosa327** [Mxater/DualSenseSupport#1]
Hi, first I wanna give you thanks for your great work.
I know this is a "secundary" tool, but very useful to test the Dualsense on pc without need to install anything.
They are other program create by Nielk1 which is focused on the triggers which let add the numbers for generate a trigger reaction. 
My request is if you could add this option to your program to have everything on only one.

**Comment by Mxater** [comment]
I dont find their program, you can send me the link for check it?

**Comment by Mxater** [comment]
I added this!
